@startuml
node Computer {
portout "USB port" as computerusb
}
node hood #line.dashed {
component "Raspberry Pi" as pi {
portin "USB-C port" as piusb
port "GPIO port" as gpiopi
portout "ethernet port" as piethernet
component Screen
}
}
node "Router / Switch / Modem" as router {
port "ethernet port" as routerethernet
}
computerusb -- piusb : USB cable
gpiopi - Screen : fixed
piethernet -- routerethernet : ethernet cable

@enduml
