@startuml
title Default hardware deployment view
node Computer {
portout "USB port" as computerusb
}
node hood #line.dashed {
component "Raspberry Pi" as pi {
portin "USB-C port" as piusb
port "GPIO port" as gpiopi
portout "ethernet port" as piethernet
component Screen
component "Shutdown button" as button
}
}
node "Router / Switch / Modem" as router {
port "ethernet port" as routerethernet
}
computerusb -- piusb : USB cable
gpiopi - button 
gpiopi - Screen 
piethernet -- routerethernet : ethernet cable

@enduml
