@startuml

skinparam monochrome true
skinparam shadowing false
skinparam defaultFontName Arial
skinparam componentStyle rectangle

title Process view of normal HTTP traffic from user

participant "Client" as CLIENT
participant "dnsmasq" as DNSLAN
participant "hood-http-handler.py\n 0.0.0.0:80" as HOODHTTP
participant "hood-tls-proxy\n 0.0.0.0:443" as HOODTLS
participant "hood-name-service.py" as HOODNAME
participant "public DNS services" as PUBDNS
participant "example.com:443" as HTTP

CLIENT -> DNSLAN: Ask example.com
DNSLAN -> CLIENT: 10.0.33.1, for example
CLIENT -> HOODHTTP: Connect to 10.0.33.1:80
CLIENT -> HOODHTTP: HTTP requests\nHost: example.com
HOODHTTP -> HOODTLS: TLS Handshake\nSNI: example.com
HOODTLS -> HOODNAME: Ask example.com
HOODNAME <-> PUBDNS: DNS over HTTPS
HOODNAME -> HOODTLS: x.x.x.x
HOODTLS -> HTTP: Connect to x.x.x.x:443
HOODTLS <-> HOODHTTP: TLS Handshakes
HOODTLS -> HOODTLS: Security checks
HOODTLS <-> HTTP: TLS Handshakes
HOODHTTP <-> HTTP: Handshake success through hood-tls-proxy
HOODHTTP -> HOODTLS: Encoded HTTP requests TLS packets
HOODTLS -> HTTP: TLS packets
HTTP -> HOODTLS: HTTP reponses encoded as TLS packets
HOODTLS -> HOODHTTP: TLS packets
HOODHTTP -> CLIENT: Decrpted plaintext HTTP responses


@enduml
